---
- name: debian | Updating Grub Timeout
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_TIMEOUT"
    line: "GRUB_TIMEOUT={{ performance_tuning_grub_timeout }}"
  become: true
  notify: update-grub
  when: performance_tuning_grub_config
